# Generated by Django 4.0.2 on 2022-02-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_books_options_alter_tags_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='books',
            name='date',
            field=models.CharField(max_length=20, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.CharField(max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='books',
            name='language',
            field=models.CharField(choices=[('RU', 'Русский'), ('UK', 'Украинский'), ('EN', 'Английский'), ('DE', 'Немецкий'), ('FR', 'Французский')], default='RU', max_length=2, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='books',
            name='presence',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='books',
            name='tags',
            field=models.ManyToManyField(to='catalog.Tags', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
