# Generated by Django 4.0.2 on 2022-02-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_books_author_alter_books_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.IntegerField(default=400, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='date',
            field=models.CharField(blank=True, default=2000, max_length=20, verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Описание'),
        ),
    ]
