# Generated by Django 4.0.2 on 2022-02-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_books_price_alter_books_date_alter_books_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='picture',
            field=models.ImageField(blank=True, upload_to='books/'),
        ),
    ]
