# Generated by Django 4.0.2 on 2022-02-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_books_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('0', 'Художественная литература'), ('1', 'Научно-популярная литература'), ('2', 'Справочная литература'), ('3', 'Документальная проза'), ('4', 'Учебная литература')], default='0', max_length=1, verbose_name='Категория'),
        ),
    ]
